[Task] Fix compiler warnings when building `picocert` (#4)
Currently, when compiling `picocert` with `-Wall` and targeting a 32-bit
system, we get compiler warnings about functions being defined and not
used:

  picocert.h:314:23: error: 'picocert_init_context' defined but not used
      [-Werror=unused-function]
  314 | static picocert_err_t picocert_init_context(
      |                       ^~~~~~~~~~~~~~~~~~~~~

Similarly, about existing defines (`PACKED`) and string formatting:

  picocert.h:581:24: error: format '%u' expects argument of type 'unsigned
      int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'}
      [-Werror=format=]
  581 |   printf("  Reserved: %u\n", picocert_get_reserved(cert));
      |                       ~^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        |     |
      |                        |     uint32_t {aka long unsigned int}
      |                        unsigned int
      |                       %lu

This patch resolves those errors.

---------

Signed-off-by: Ford Peprah <ford@squareup.com>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>